name: "🐛 Fix"
description: 记录一个需要修复的 bug
title: "[Fix] "
labels: ["type/fix"]
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充信息
    validations:
      required: false
