name: "🧪 Test"
description: 测试用例编写或测试相关问题
title: "[Test] "
labels: ["type/test"]
body:
  - type: textarea
    id: description
    attributes:
      label: 测试描述
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充信息
    validations:
      required: false
